--- 
title: "Introduction to Regression Analysis in R"
author: "Kayleigh Keller"
date: ""
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
description: "TBD"
---

<!-- `r Sys.Date()` -->

# Preface {-}

This book emerged from the course notes I developed as instructor for a course (STAT 341) at Colorado State University. My intent is for this to serve as a resource for an introductory-level undergraduate course on regression methods. Emphasis is on the application of methods, and so mathematical concepts are intertwined with examples using the R computing language. 

This book assumes an understanding of basic statistical concepts, including expectation and variance. The examples almost exclusively use the R programming language, and basic familiarity with R is assumed.

I am continuing to expand and revise the information in this book. If you find any errors or have any feedback, please 
<a href="https://www.kellerbiostat.com/contact.html"> contact me</a> to let me know!

## License {-}

All content is copyright &copy; 2020-2023 Kayleigh Keller. The work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.
